function dh0 = get_dh0(in1,in2,in3,theta_begin,theta_end)
%GET_DH0
%    DH0 = GET_DH0(IN1,IN2,IN3,THETA_BEGIN,THETA_END)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-Dec-2016 15:18:15

dq4 = in2(4,:);
dq5 = in2(5,:);
dq6 = in2(6,:);
dq7 = in2(7,:);
dh0 = [dq4.*(1.0./2.0)+dq5.*(1.0./2.0);dq6.*(1.0./2.0)+dq7.*(1.0./2.0);-dq4+dq5;-dq6+dq7];
